name: AtriFlow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

env:
  CACHE_NUMBER: 1 # Increase to reset cache

jobs:
  check-code:
    name: Run linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and project
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install '.[test]'

      - name: Run linting and checks
        run: |
          bash linting.sh

